pipeline{
    agent any

    tools{

    }
    
    stages{
        stage("Build-App"){
            steps{
             echo 'building app with npm'
             dir('.'){
                sh 'npm i'
                sh 'npm start'
             }
            }
        }
    }

    post{
        always {
        echo 'done!' 
        }
    }
}